#!/usr/bin/env bash
# Generate the deployment's credentials. Never prints one.
#
# Upstream's compose ships `octopus:octopus`. rayf P-0007 C1b requires generated
# credentials replacing example values, and C4 requires they never appear in Git
# or logs -- so this writes a 0600 .env beside the compose file, which .gitignore
# already excludes, and reports only lengths.
#
# Idempotent by refusal, not by overwrite: rotating the database password out from
# under a running PostgreSQL volume locks the deployment out of its own data,
# because the password is baked into the volume at initdb time. Pass --rotate-app
# to regenerate only the values that are safe to change.
set -euo pipefail
umask 077

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$DIR/.env"
ROTATE_APP=0
[ "${1:-}" = "--rotate-app" ] && ROTATE_APP=1

secret() { openssl rand -base64 36 | tr -d '\n/+=' | cut -c1-40; }

if [ -f "$ENV_FILE" ] && [ "$ROTATE_APP" -eq 0 ]; then
  echo "refusing: $ENV_FILE exists." >&2
  echo "The PostgreSQL password is fixed at initdb time; regenerating it locks the" >&2
  echo "deployment out of its existing volume. Use --rotate-app for the app secrets," >&2
  echo "or remove the volume deliberately if you mean to start over." >&2
  exit 1
fi

if [ "$ROTATE_APP" -eq 1 ] && [ -f "$ENV_FILE" ]; then
  # Keep the database credentials exactly as they are; replace the rest.
  PG_USER="$(grep -E '^POSTGRES_USER=' "$ENV_FILE" | cut -d= -f2-)"
  PG_PASS="$(grep -E '^POSTGRES_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)"
  PG_DB="$(grep -E '^POSTGRES_DB=' "$ENV_FILE" | cut -d= -f2-)"
else
  PG_USER="octopus_$(openssl rand -hex 4)"
  PG_PASS="$(secret)"
  PG_DB="octopus"
fi

{
  echo "# Generated by generate-secrets.sh. Never commit this file."
  echo "POSTGRES_USER=$PG_USER"
  echo "POSTGRES_PASSWORD=$PG_PASS"
  echo "POSTGRES_DB=$PG_DB"
  echo "BETTER_AUTH_SECRET=$(secret)"
  echo "ENCRYPTION_KEY=$(secret)"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "wrote $ENV_FILE (mode $(stat -c %a "$ENV_FILE" 2>/dev/null || stat -f %Lp "$ENV_FILE"))"
while IFS='=' read -r key value; do
  case "$key" in ''|\#*) continue ;; esac
  printf '  %-22s %s chars\n' "$key" "${#value}"
done < "$ENV_FILE"
