#!/usr/bin/env bash
# Generate the deployment's credentials. Never prints one.
#
# Upstream's compose ships `octopus:octopus`. rayf P-0007 C1b requires generated
# credentials replacing example values, and C4 requires they never appear in Git
# or logs -- so this writes a 0600 .env beside the compose file, which .gitignore
# already excludes, and reports only lengths.
#
# Idempotent by refusal, not by overwrite: rotating the database password out from
# under a running PostgreSQL volume locks the deployment out of its own data,
# because the password is baked into the volume at initdb time. Pass --rotate-app
# to regenerate only the values that are safe to change.
#
# `OCTOPUS_DATA_KEY` is what encrypts stored credentials. `apps/web/lib/crypto.ts`
# reads it, and falls back to `sha256(BETTER_AUTH_SECRET)` when it is unset -- which
# is the trap this script exists to keep shut. Without a data key, rotating the
# "app secret" IS rotating the encryption key, and every encrypted row stops being
# readable. So a data key is generated up front and carried across every rotation.
# With it set, BETTER_AUTH_SECRET is only a session secret and is genuinely safe to
# replace, which is why the application splits the two in the first place.
set -euo pipefail
umask 077

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$DIR/.env"
ROTATE_APP=0
[ "${1:-}" = "--rotate-app" ] && ROTATE_APP=1

secret() { openssl rand -base64 36 | tr -d '\n/+=' | cut -c1-40; }

if [ -f "$ENV_FILE" ] && [ "$ROTATE_APP" -eq 0 ]; then
  echo "refusing: $ENV_FILE exists." >&2
  echo "The PostgreSQL password is fixed at initdb time; regenerating it locks the" >&2
  echo "deployment out of its existing volume. Use --rotate-app for the app secrets," >&2
  echo "or remove the volume deliberately if you mean to start over." >&2
  exit 1
fi

value_of() { grep -E "^$1=" "$ENV_FILE" | head -1 | cut -d= -f2-; }

if [ "$ROTATE_APP" -eq 1 ] && [ -f "$ENV_FILE" ]; then
  # Keep the database credentials, and keep the data key: it is what decrypts
  # everything already written.
  PG_USER="$(value_of POSTGRES_USER)"
  PG_PASS="$(value_of POSTGRES_PASSWORD)"
  PG_DB="$(value_of POSTGRES_DB)"
  DATA_KEY="$(value_of OCTOPUS_DATA_KEY)"
  if [ -z "$DATA_KEY" ]; then
    echo "refusing: $ENV_FILE has no OCTOPUS_DATA_KEY, so BETTER_AUTH_SECRET is what" >&2
    echo "encrypts the data (crypto.ts falls back to sha256 of it). Rotating it would" >&2
    echo "make every encrypted row unreadable. Add a data key first -- see the README." >&2
    exit 1
  fi
else
  PG_USER="octopus_$(openssl rand -hex 4)"
  PG_PASS="$(secret)"
  PG_DB="octopus"
  # 32 bytes, hex. crypto.ts rejects anything else, and it says so.
  DATA_KEY="$(openssl rand -hex 32)"
fi

# Written to a temporary file and moved into place, so an interrupted run cannot
# leave a half-written .env -- which, for the file holding the data key, means a
# deployment that cannot read its own database.
TMP_ENV="$(mktemp "$DIR/.env.XXXXXX")"
chmod 600 "$TMP_ENV"
{
  echo "# Generated by generate-secrets.sh. Never commit this file."
  echo "POSTGRES_USER=$PG_USER"
  echo "POSTGRES_PASSWORD=$PG_PASS"
  echo "POSTGRES_DB=$PG_DB"
  echo "BETTER_AUTH_SECRET=$(secret)"
  echo "OCTOPUS_DATA_KEY=$DATA_KEY"
  # Signs the short-lived state on the GitHub install redirect. The application
  # warns at boot when it is missing and then throws inside the redirect, so
  # without it the connect flow fails at the click rather than at start-up.
  echo "GITHUB_STATE_SECRET=$(secret)"
} > "$TMP_ENV"

# Anything this script does not own is carried across verbatim -- provider keys,
# OAuth credentials, embedding settings. Rewriting the file to only the values
# generated here would delete them.
#
# ENCRYPTION_KEY is in the owned list without being written: the application reads
# no such variable, so an .env carrying one loses it here rather than keeping a
# credential-shaped value that protects nothing.
if [ -f "$ENV_FILE" ]; then
  MINE="POSTGRES_USER|POSTGRES_PASSWORD|POSTGRES_DB|BETTER_AUTH_SECRET|OCTOPUS_DATA_KEY|GITHUB_STATE_SECRET|ENCRYPTION_KEY"
  grep -vE "^($MINE)=" "$ENV_FILE" | grep -vE '^# Generated by generate-secrets\.sh' >> "$TMP_ENV" || true
fi
mv "$TMP_ENV" "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "wrote $ENV_FILE (mode $(stat -c %a "$ENV_FILE" 2>/dev/null || stat -f %Lp "$ENV_FILE"))"
while IFS='=' read -r key value; do
  case "$key" in ''|\#*) continue ;; esac
  printf '  %-22s %s chars\n' "$key" "${#value}"
done < "$ENV_FILE"
