import type { RulePack } from "./types";

/**
 * Always-on security pack — OWASP Top 10 + high-value CWE Top 25. Language-
 * agnostic (languages: ["*"]). Tag a Security finding with the matching `cwe`
 * only when it maps to one of these rules.
 */
export const SECURITY_PACK: RulePack = {
  key: "security",
  title: "Security rulepack (OWASP / CWE)",
  rules: [
    {
      id: "sec-sqli",
      cwe: "CWE-89",
      owasp: "A03:2021-Injection",
      title: "SQL/NoSQL injection",
      signal: "user input concatenated/interpolated into a query instead of parameterized.",
      languages: ["*"],
      severityHint: "🔴",
      remediation: "use parameterized queries / an ORM binding.",
      example: "`db.query('… WHERE id = $1', [id])` not `` `… id = ${id}` ``.",
    },
    {
      id: "sec-xss",
      cwe: "CWE-79",
      owasp: "A03:2021-Injection",
      title: "Cross-site scripting",
      signal: "unsanitized input rendered into HTML/DOM (innerHTML, dangerouslySetInnerHTML, template).",
      languages: ["*"],
      severityHint: "🔴",
      remediation: "escape/encode on output or use a safe templating API.",
      example: "render via text nodes, not `el.innerHTML = userInput`.",
    },
    {
      id: "sec-authz",
      cwe: "CWE-639",
      owasp: "A01:2021-Broken Access Control",
      title: "Broken access control / IDOR",
      signal: "a resource fetched by a client-supplied id without an ownership/role check.",
      languages: ["*"],
      severityHint: "🔴",
      remediation: "scope the query to the caller (org/user) and verify role.",
      example: "`where: { id, orgId: session.orgId }` not `where: { id }`.",
    },
    {
      id: "sec-secret",
      cwe: "CWE-798",
      owasp: "A07:2021-Identification and Authentication Failures",
      title: "Hardcoded secret / credential",
      signal: "an API key, password, token, or private key literal in code.",
      languages: ["*"],
      severityHint: "🔴",
      remediation: "read from env/secret store; rotate the exposed value.",
      example: "`process.env.API_KEY` not `const key = 'sk-…'`.",
    },
    {
      id: "sec-ssrf",
      cwe: "CWE-918",
      owasp: "A10:2021-SSRF",
      title: "Server-side request forgery",
      signal: "a server fetch to a URL derived from user input without host allowlisting.",
      languages: ["*"],
      severityHint: "🟠",
      remediation: "validate against an allowlist; block internal/link-local ranges.",
      example: "reject `169.254.*`, `localhost`, and non-allowlisted hosts.",
    },
    {
      id: "sec-deser",
      cwe: "CWE-502",
      owasp: "A08:2021-Software and Data Integrity Failures",
      title: "Insecure deserialization / eval",
      signal: "eval()/pickle/native deserialization on untrusted data.",
      languages: ["*"],
      severityHint: "🟠",
      remediation: "parse with a safe format (JSON) and validate a schema.",
      example: "`JSON.parse` + zod, never `eval(userInput)`.",
    },
    {
      id: "sec-path",
      cwe: "CWE-22",
      owasp: "A01:2021-Broken Access Control",
      title: "Path traversal",
      signal: "user input used in a filesystem path without normalization/containment.",
      languages: ["*"],
      severityHint: "🟠",
      remediation: "resolve and assert the path stays within an allowed root.",
      example: "reject resolved paths that escape the base dir (`..`).",
    },
    {
      id: "sec-ratelimit",
      cwe: "CWE-770",
      owasp: "A04:2021-Insecure Design",
      title: "Missing rate limit on sensitive endpoint",
      signal: "a new auth/costly/enumeration endpoint with no rate limiting.",
      languages: ["*"],
      severityHint: "🟡",
      remediation: "apply per-principal rate limiting.",
      example: "limit login/password-reset/verification routes.",
    },
  ],
};
